# Generated by Django 2.2.7 on 2019-12-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
