# Generated by Django 2.2.7 on 2019-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservations_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
