# Generated by Django 2.2.7 on 2019-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20191218_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='owner',
        ),
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
